project:
  type: website

website:
  title: "webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: spin_operator.md
        text: Spin Operator

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



