project:
  type: website

website:
  title: "webpage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - href: spin_operator.md
        text: Spin Operator
    right:
      - icon: envelope
        href: mailto:marius.kadek@uit.no
      - icon: twitter
        href: https://twitter.com/KadekMarius
      - icon: google
        href: https://scholar.google.com/citations?user=5BmKNMkAAAAJ&hl=en
      - icon: github
        href: https://github.com/mkadek


format:
  html:
#   theme: sandstone
    theme: yeti
    css: styles.css
    toc: true



